name: Tangos DB Build Test
on: [push, pull_request]
jobs:
  build_db:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
      - uses: actions/checkout@v4
      - name: Install requirements
        run: |
          pip install -r pip-requirements.txt
          pip install -r dev-requirements.txt
          pip install -r build_tangos_db/requirements.txt
      - name: Build the tangos DB
        run: |
          cd build_tangos_db
          wget https://nbody.shop/NUGS128.tar.gz
          mkdir -p $HOME/data/
          tar -xvzf NUGS128.tar.gz -C $HOME/data
          source config_vars
          ./build_tangos.sh
      - name: Run the tests
        run: |
          source config_vars
          pytest
