name: Volume IC Build Test
on: [push, pull_request]
jobs:
  build_ic:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
      - uses: actions/checkout@v4
      - name: Install requirements
        run: |
          pip install -r pip-requirements.txt
          pip install -r dev-requirements.txt
          pip install -r build_volume_ic/requirements.txt
      - name: Build small test IC
        run: |
          cd build_volume_ic
          ./build.sh -t
      - name: Check that the md5 checksums of the outputs are correct
        run: |
          cd build_volume_ic
          md5sum -c .checksums.txt
