name: Flake8
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
      - uses: actions/checkout@v4
      - name: Build dev environment
        run: |
          pip install -r pip-requirements.txt
          pip install -r dev-requirements.txt
      - name: Run Black formatter
        run: |
          black --check .
      - name: Run flake8 linter
        run: |
          flake8 .
      - name: Run isort to check imports
        run: |
          isort --check-only .
